FROM gcc:10.4

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

RUN apt-get update -y && \
    apt-get install git cmake nodejs -y

RUN echo $(gcc --version)
RUN echo $(cmake --version)
RUN echo $(node --version)

WORKDIR /app
COPY . .

RUN mkdir build && \
    cd build && \
    cmake ../ && \
    cmake --build .

# RUN mkdir temp && \
#     cd temp && \
#     git clone https://github.com/chriswoodle/wuw-corpus-ii.git  –depth 1

RUN node ./scripts/build_operator_model.js
